-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 16:30:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema discente
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `discente` ;

-- -----------------------------------------------------
-- Schema discente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discente` DEFAULT CHARACTER SET utf8 ;
USE `discente` ;

-- -----------------------------------------------------
-- Table `discente`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Pais` ;

CREATE TABLE IF NOT EXISTS `discente`.`Pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Estado` ;

CREATE TABLE IF NOT EXISTS `discente`.`Estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(3) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `discente`.`Cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `discente`.`Bairro` (
  `id_bairro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Logradouro` ;

CREATE TABLE IF NOT EXISTS `discente`.`Logradouro` (
  `id_logradouro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_logradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `discente`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cidade` INT NULL,
  `id_bairro` INT NULL,
  `id_logradouro` INT NULL,
  `cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Titulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Titulo` ;

CREATE TABLE IF NOT EXISTS `discente`.`Titulo` (
  `id_titulo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Docente` ;

CREATE TABLE IF NOT EXISTS `discente`.`Docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `link_lattes` VARCHAR(128) NULL,
  `email` VARCHAR(45) NOT NULL,
  `numero_residencia` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `carga_horaria_programa` INT NOT NULL,
  `situacao` INT NOT NULL,
  `id_titulo` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Discente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Discente` ;

CREATE TABLE IF NOT EXISTS `discente`.`Discente` (
  `id_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `sobrenome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(20) NULL,
  `cpf` VARCHAR(20) NULL,
  `username` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `link_lattes` VARCHAR(90) NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_endereco` INT NOT NULL,
  `numero_residencia` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `id_docente` INT NOT NULL,
  `isAceito` TINYINT NULL,
  `situacao` INT NOT NULL,
  `id_titulo` INT NOT NULL,
  `sexo` INT NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `passaporte` VARCHAR(45) NULL,
  `id_nacionalidade` INT NOT NULL,
  PRIMARY KEY (`id_discente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `discente`.`Instituicao` (
  `id_instituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `sigla` VARCHAR(10) NULL,
  `id_tipo_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`CargoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`CargoDiscente` ;

CREATE TABLE IF NOT EXISTS `discente`.`CargoDiscente` (
  `id_cargo_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_cargo_discente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`DiscenteCargoInstituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`DiscenteCargoInstituicao` ;

CREATE TABLE IF NOT EXISTS `discente`.`DiscenteCargoInstituicao` (
  `id_discente` INT NOT NULL,
  `id_instituicao` INT NOT NULL,
  `id_cargo_discente` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`TipoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`TipoDiscente` ;

CREATE TABLE IF NOT EXISTS `discente`.`TipoDiscente` (
  `id_tipo_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_discente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discente`.`DiscenteTipoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discente`.`DiscenteTipoDiscente` ;

CREATE TABLE IF NOT EXISTS `discente`.`DiscenteTipoDiscente` (
  `id_tipo_discente` INT NOT NULL,
  `id_discente` INT NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NULL,
  `isAtual` TINYINT NULL,
  PRIMARY KEY (`id_tipo_discente`, `id_discente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
