-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 21:13:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ppgtgs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ppgtgs` ;

-- -----------------------------------------------------
-- Schema ppgtgs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppgtgs` DEFAULT CHARACTER SET utf8 ;
USE `ppgtgs` ;

-- -----------------------------------------------------
-- Table `ppgtgs`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Pais` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Estado` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(3) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_Estado_Pais1_idx` (`id_pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_Cidade_Estado1_idx` (`id_estado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Bairro` (
  `id_bairro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Logradouro` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Logradouro` (
  `id_logradouro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_logradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cidade` INT NULL,
  `id_bairro` INT NULL,
  `id_logradouro` INT NULL,
  `cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_Endereco_Cidade1_idx` (`id_cidade` ASC) VISIBLE,
  INDEX `fk_Endereco_Bairro1_idx` (`id_bairro` ASC) VISIBLE,
  INDEX `fk_Endereco_Logradouro1_idx` (`id_logradouro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Titulacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Titulacao` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Titulacao` (
  `id_titulo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Docente` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `link_lattes` VARCHAR(128) NULL,
  `email` VARCHAR(45) NOT NULL,
  `numero_residencia` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `carga_horaria_programa` INT NOT NULL,
  `situacao` INT NOT NULL,
  `id_titulo` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_docente`),
  INDEX `fk_Docente_Titulo1_idx` (`id_titulo` ASC) VISIBLE,
  INDEX `fk_Docente_Endereco1_idx` (`id_endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Discente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Discente` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Discente` (
  `id_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `sobrenome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(20) NULL,
  `cpf` VARCHAR(20) NULL,
  `username` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `link_lattes` VARCHAR(90) NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_endereco` INT NOT NULL,
  `numero_residencia` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `id_docente` INT NOT NULL,
  `isAceito` TINYINT NULL,
  `situacao` INT NOT NULL,
  `id_titulo` INT NOT NULL,
  `sexo` INT NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `passaporte` VARCHAR(45) NULL,
  `id_nacionalidade` INT NOT NULL,
  PRIMARY KEY (`id_discente`),
  INDEX `fk_Discente_EnderecoDiscente1_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_Discente_Docente1_idx` (`id_docente` ASC) VISIBLE,
  INDEX `fk_Discente_Titulo1_idx` (`id_titulo` ASC) VISIBLE,
  INDEX `fk_Discente_Pais1_idx` (`id_nacionalidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Instituicao` (
  `id_instituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `sigla` VARCHAR(10) NULL,
  `id_tipo_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`CargoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`CargoDiscente` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`CargoDiscente` (
  `id_cargo_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_cargo_discente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`DiscenteCargoInstituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`DiscenteCargoInstituicao` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`DiscenteCargoInstituicao` (
  `id_discente` INT NOT NULL,
  `id_instituicao` INT NOT NULL,
  `id_cargo_discente` INT NOT NULL,
  INDEX `fk_Discente_has_Instituicao_Instituicao1_idx` (`id_instituicao` ASC) VISIBLE,
  INDEX `fk_Discente_has_Instituicao_Discente1_idx` (`id_discente` ASC) VISIBLE,
  INDEX `fk_DiscenteInstituicao_CargoDiscente1_idx` (`id_cargo_discente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`TipoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`TipoDiscente` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`TipoDiscente` (
  `id_tipo_discente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_discente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`DiscenteTipoDiscente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`DiscenteTipoDiscente` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`DiscenteTipoDiscente` (
  `id_tipo_discente` INT NOT NULL,
  `id_discente` INT NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NULL,
  `isAtual` TINYINT NULL,
  PRIMARY KEY (`id_tipo_discente`, `id_discente`),
  INDEX `fk_TipoDiscente_has_Discente_Discente1_idx` (`id_discente` ASC) VISIBLE,
  INDEX `fk_TipoDiscente_has_Discente_TipoDiscente1_idx` (`id_tipo_discente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`TipoProjeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`TipoProjeto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`TipoProjeto` (
  `idTipoProjeto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`NivelImpacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`NivelImpacto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`NivelImpacto` (
  `idNivelImpacto` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idNivelImpacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Projeto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `TipoProjeto_idTipoProjeto` INT NOT NULL,
  `NivelImpacto_idNivelImpacto` INT NOT NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_Projeto_TipoProjeto1_idx` (`TipoProjeto_idTipoProjeto` ASC) VISIBLE,
  INDEX `fk_Projeto_NivelImpacto1_idx` (`NivelImpacto_idNivelImpacto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`TipoProducaoIntelectual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`TipoProducaoIntelectual` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`TipoProducaoIntelectual` (
  `idTipoProducaoIntelectual` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProducaoIntelectual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Qualis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Qualis` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Qualis` (
  `idQualis` INT NOT NULL AUTO_INCREMENT,
  `classificacao` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idQualis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`ProducaoIntelectual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`ProducaoIntelectual` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`ProducaoIntelectual` (
  `idProducaoIntelectual` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `TipoProducaoIntelectual_idTipoProducaoIntelectual` INT NOT NULL,
  `Projeto_idProjeto` INT NULL,
  `Qualis_idQualis` INT NOT NULL,
  PRIMARY KEY (`idProducaoIntelectual`),
  INDEX `fk_ProducaoIntelectual_TipoProducaoIntelectual1_idx` (`TipoProducaoIntelectual_idTipoProducaoIntelectual` ASC) VISIBLE,
  INDEX `fk_ProducaoIntelectual_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  INDEX `fk_ProducaoIntelectual_Qualis1_idx` (`Qualis_idQualis` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`TipoImpacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`TipoImpacto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`TipoImpacto` (
  `idTipoImpacto` INT NOT NULL AUTO_INCREMENT,
  `dimensao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipoImpacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Discente_has_ProducaoIntelectual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Discente_has_ProducaoIntelectual` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Discente_has_ProducaoIntelectual` (
  `Discente_id_discente` INT NOT NULL,
  `ProducaoIntelectual_idProducaoIntelectual` INT NOT NULL,
  PRIMARY KEY (`Discente_id_discente`, `ProducaoIntelectual_idProducaoIntelectual`),
  INDEX `fk_Discente_has_ProducaoIntelectual_ProducaoIntelectual1_idx` (`ProducaoIntelectual_idProducaoIntelectual` ASC) VISIBLE,
  INDEX `fk_Discente_has_ProducaoIntelectual_Discente1_idx` (`Discente_id_discente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Discente_has_Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Discente_has_Projeto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Discente_has_Projeto` (
  `Discente_id_discente` INT NOT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  INDEX `fk_Discente_has_Projeto_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  INDEX `fk_Discente_has_Projeto_Discente1_idx` (`Discente_id_discente` ASC) VISIBLE,
  PRIMARY KEY (`Discente_id_discente`, `Projeto_idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Projeto_has_TipoImpacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Projeto_has_TipoImpacto` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Projeto_has_TipoImpacto` (
  `Projeto_idProjeto` INT NOT NULL,
  `TipoImpacto_idTipoImpacto` INT NOT NULL,
  PRIMARY KEY (`Projeto_idProjeto`, `TipoImpacto_idTipoImpacto`),
  INDEX `fk_Projeto_has_TipoImpacto_TipoImpacto1_idx` (`TipoImpacto_idTipoImpacto` ASC) VISIBLE,
  INDEX `fk_Projeto_has_TipoImpacto_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgtgs`.`Docente_has_ProducaoIntelectual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppgtgs`.`Docente_has_ProducaoIntelectual` ;

CREATE TABLE IF NOT EXISTS `ppgtgs`.`Docente_has_ProducaoIntelectual` (
  `Docente_id_docente` INT NOT NULL,
  `ProducaoIntelectual_idProducaoIntelectual` INT NOT NULL,
  PRIMARY KEY (`Docente_id_docente`, `ProducaoIntelectual_idProducaoIntelectual`),
  INDEX `fk_Docente_has_ProducaoIntelectual_ProducaoIntelectual1_idx` (`ProducaoIntelectual_idProducaoIntelectual` ASC) VISIBLE,
  INDEX `fk_Docente_has_ProducaoIntelectual_Docente1_idx` (`Docente_id_docente` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
